### PR TITLE
adding load-texture to the mix...

### PR DESCRIPTION
**Pull request by serialhex**
Small change to add `load-texture`.  I had started writing my own bindings, but since this was here & 95% what I wrote anyway, I figured I'd contribute rather than compete.

### CODE REVIEW

**Comment by fitzsim** [comment]
If you're still interested in merging this, would you mind updating this PR so that it is mergeable again, and also provide a minimal test case so that I can test texture loading on my own setup?  If you're no longer interested, let me know and I'll close this PR.

**Comment by serialhex** [comment]
ERHMEHGHERD!!! 7 years, I totally forgot about this!  I can look at it, clean it up & get it working, but it may take a few days.  If you're fine with that, cool!  If not, go ahead and close, it's a pretty simple function, and should be easily reproduced by almost anyone.

**Comment by fitzsim** [comment]
Good to hear from you.  Sure, a few days is fine.  I'll watch for the update, thanks.

**Comment by serialhex** [comment]
Hey @fitzsim I've been busy & haven't had a chance to even think about this besides like... right now.  Most of the changes is autogenerated stuff from the `*.spec` files, which don't really matter, the core is a 3 line function & an export.  I'm just gonna close this, and if someone wants to copy-pasta the function & write some tests I'll let them have the credit.

Sorry I couldn't finish this.  Thank you & take care!

**Pull request closed without merging**
